### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by abbeycc** [apulverizer/pyspatialopt#7]
Hi, Aaron!
I have two questions.
1. If I change shapefile from "facility_service_areas.shp" to "facility2_service_areas.shp" in binary_mclp_arcpy.py , there will be a mistake. I don't know the reason for that.
2. If I want the selected facilities have no overlap in their service areas, how can I add some restrictions in the code?

Thank you so much!

**Comment by apulverizer** [comment]
For the first question, what do you mean there will be a mistake? What happens?

For the second question, I believe you'd have to modify or add another constraint to the problem that made it so each demand point could only covered once, not 2 or 3 or more times. I believe you'd change the code around this line https://github.com/apulverizer/pyspatialopt/blob/master/pyspatialopt/models/covering.py#L214

You'll have to use the classes/objects provided in [Pulp](https://pythonhosted.org/PuLP/) to do that. I think it will be just a line or two of changes.

**Comment by abbeycc** [comment]
Thank you so much for your reply!!
For the first question,  I got an empty set of facility id whether solved by gurobi or GLPK. I also used my own data in mclp-cc, and got no results. 
![1](https://user-images.githubusercontent.com/42798036/44793087-0893f500-abd8-11e8-81c6-da1e2826648e.png)
![2](https://user-images.githubusercontent.com/42798036/44793090-092c8b80-abd8-11e8-883a-fcfb907a3cde.png)

**Comment by apulverizer** [comment]
Interesting. I'll take a look when I get a chance (probably won't be for a few weeks though).

**Comment by abbeycc** [comment]
OK, thank you! Both mclp and mclp-cc have the same problem.

**Comment by apulverizer** [comment]
Hi @abbeycc I think I figured out what was causing your issue. 
The model is solved correctly but when it is extracting the results it's looking for the wrong `string` for variable names. 

In the example, you also need to modify this line:
https://github.com/apulverizer/pyspatialopt/blob/master/examples/binary_mclp_arcpy.py#L46 
to use `facility2_service_areas` instead of `facility_service_areas`.

The reason this is necessary is because in the examples, the variable names are not specified, they are harvested from the layer/file name. You can see this happening in https://github.com/apulverizer/pyspatialopt/blob/master/pyspatialopt/analysis/arcpy_analysis.py#L153

This could be avoided in the sample by modifying this line https://github.com/apulverizer/pyspatialopt/blob/master/examples/binary_mclp_arcpy.py#L33 to add a named argument to specify the name like `fl_variable_name="facility_service_areas"`

Hope this helps. I bet it's also the issue you are seeing when using your own data.

**Comment by abbeycc** [comment]
Yes, it can work now!
Thank you so much!
Have a nice day : P
